### ISSUE TITLE
Camera synchronization issue

### ISSUE THREAD

**Issue by rlin264** [DukeRobotics/robosub-ros#146]
Appears that right camera is publishing faster (sort of random, but slowly increasing difference in frames received by right camera)
Potential fixes:
- Publish only when both cameras can publish properly
- Start both cameras simultaneously

**Comment by neildhar** [comment]
just out of curiosity, did stereo_image_proc complain about this?

**Comment by rlin264** [comment]
I fixed it yesterday. Stereo cameras are working now
