### ISSUE TITLE
Upgrade to ROS Noetic

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#216]
This issue tracks the various components required to upgrade our systems to ROS Noetic and Ubuntu 20.04. Checkmarks indicate that the package has been made available for ROS Noetic.

ROS dependencies for onboard image
- [x] ros-core
- [x] cv-bridge
- [x] tf
- [x] robot-localization
- [x] pid
- [ ] camera-info-manager-py
- [x] rosserial
- [x] rosserial-arduino
- [x] libg2o

ROS dependencies for landside image
- [x] geometry2
- [x] rviz
- [x] joy
- [x] rosbridge-suite

NVIDIA dependencies
- [ ] NVIDIA releases L4T image with Ubuntu 20.04

**Comment by neildhar** [comment]
You could build Noetic and camera-info-manager from source. Someone from Nvidia has done an 18.04 image with Noetic preinstalled.

https://github.com/dusty-nv/jetson-containers/blob/master/Dockerfile.ros.noetic
