### ISSUE TITLE
C++ Simulation Rewrite

### ISSUE THREAD

**Issue by puzzler7** [DukeRobotics/robosub-ros#232]
- [ ] C++ Simulation Rewrite
    - [ ] Figure out how to compile plugin
    - [ ] Write new C++buoyancy/thruster code
    - [ ] Create Lua interface (as small as possible)
    - [ ] Verify communication code still works
    - [ ] Test plugin
    - [ ] Perfect plugin physics

**Comment by muthuArivoli** [comment]
Superseded by #275.
