### ISSUE TITLE
Task Planning Spring 2021

### ISSUE THREAD

**Issue by echang264** [DukeRobotics/robosub-ros#245]
**Spring Semester Goals:**
- [x] CV integration
- [ ] prequalification
- [ ] gate task using CV -- waiting to test as of 2/6/21
- [x] move to a position such that a point from CV is in a certain part of the frame
- [ ] move to a position such that a bounding box from CV is in a certain part of the frame
- [ ] test move to positions based on CV
- [ ] servo interaction - use rosservice in #251 (and [Offboard Comms](https://github.com/DukeRobotics/robosub-ros/tree/master/onboard/catkin_ws/src/offboard_comms)) to control servos
- [ ] documentation
- [ ] organizing script files
- [ ] support running in response to a switch (could include LED display) - for new bot, mayyyybe Cthulhu
- [ ] integrate hydrophones

**Goals for 3/13/21**
- [ ] fix local->global transform bug
- [ ] change velocity to only publish local velocities to desired_twist topic

**Goals for 3/6/21**
- [ ] Update gate task to use RepeatTask()
- [ ] think about how to clean up gate task, style task, file organization
- [ ] documentation
- [ ] add logs updates as task planning runs
- [ ] condense IndSimul and DepSimul tasks to one
- [x] task-planning PR

**Goals for 2/6/21**
- [ ] Get Robert set up with simulation (@AndrewCouncil)
- [ ] test gate algo outside of pool

**Goals for 1/30/2021**
- [x] Integrate task planning with CV Object (listen to CV object)  @azhou202 
- [x] implement gate algorithm that centers gate in frame (using below function) @echang264 
- [x] implement vertical centering (i.e. depth) for above algo
- [x] function to parse CV gate and tick object, determining where robot facing @rabinowitz @Brokemia 
- [x] modify style task to use low level move tasks  @AndrewCouncil 
- [x] get Robert set up with Docker 
- [x] stretch: Robert finishes ROS tutorials (depending on installation success)
- [x] override restart() method of simul_tasks to include child tasks or restart child tasks in _on_task_start of simul_tasks

**Comment by ShaanGondalia** [comment]
Closing, stale issue.
