### ISSUE TITLE
Accelerate acoustics with numpy

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#265]
## Background
Our acoustics code is math intensive, and while certain computations in acoustics uses numpy/scipy, most of the data is then converted back to lists and passed around as regular lists. Rather than doing these conversions of list->array->list, ideally all code should be using numpy arrays. This would speed up the acoustics code, and would simplify/reduce the code in some of the places that the conversion to list/array takes place.

## Task
Most work should be in the acoustics_math python module, with functions being modified to take in the appropriate numpy arrays. Note that there will probably need to be modifications in the Guesser and Processor, so the input is converted appropriately to numpy arrays instead of being stored as lists.

**Comment by mbryant2025** [comment]
Plan is to rewrite this part of the acoustics code, no need to refactor
