### ISSUE TITLE
Unify readme structure across packages

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#267]
## Background
While we do have a readme for each package in our codebase, the readmes are vastly different with regards to their structure and content. It would be nice to have the same structure across all the readmes, allowing club members to easily find/access information within each readme.

## Task
First, design a standard structure for writing readmes. Make sure to review your design with the CS leads (and ideally add a link to the doc to this issue). Upon approval of the design, modify the various readmes to fit this structure, and perhaps add a guide or other documentation on how new readmes should be written.

**Comment by vedarshshah** [comment]
While it is true that the READMEs are vastly different in structure and content, this is for good reason as each package is unique and has different documentation requirements. Reformatting all the READMEs would take a large amount of time that does not directly contribute to improving the robot and would result in minimal, if not any, improvements to our documentation.
