### ISSUE TITLE
Add models of competition objects to simulation

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#303]
Need to add all the models of objects from competition to simulation. At the end, ideally, we should have a scene representing each task (with only the necessary objects in it for the task), and a overall big scene representing the competition (with all objects and scenes), to make it easy for task planning to test.

List of objects to be modeled:
Gate
Buoy
Choose Your Side Images
Bin
Octagon
Path Markers

**Comment by samuel-thompsonn** [comment]
On the [add-sim-models branch](https://github.com/DukeRobotics/robosub-ros/tree/add-sim-models/landside/catkin_ws/src/simulation/personal/models) we have some basic rectangular prisms with the same dimensions as the contest props for the following:
- Gate
- Image of each type, from the ['Choose Your Side'](https://robonationforum.vbulletin.net/forum/robosub/robosub-2021/3555-choose-your-side-gate) task
- Buoy of each type, from the ['Make the Grade'](https://robonationforum.vbulletin.net/forum/robosub/robosub-2021/3558-make-the-grade-buoys) task
- Bin without lid
- Octagon (Octagon.ttm is a box, and Octagon_2.ttm is an actual octagon)
- Straight path marker
- Torpedo

**Comment by vedarshshah** [comment]
This issue was written for CoppeliaSim, which we have decided to stop using. We will create new models for the latest competition props for our new sim.
