### ISSUE TITLE
Create Gate Task based on CV depth data

### ISSUE THREAD

**Issue by AndrewCouncil** [DukeRobotics/robosub-ros#308]
Need to create a new Gate Task that makes use of CV depth data. This should resolve the problem where the gate could be flipped across the xz plane of the local coordinate system and the robot would not be able to sense the difference in relative angle. By using the depth of the left and right side, this issue is remedied and the robot can accurately enter perpendicularly.

Gate task procedure:
- Move in positive x, positive y, negative z to get away from dock slightly and deep enough to see whole gate
- Rotate in negative yaw with constant velocity until gate is seen fully, then hold position
- Use bounding box of left and right to calculate rectangle of gate profile in 3D global coordinate system
- Extrude line of some arbitrary lead distance (about a meter) from the profile rectangle and move robot to endpoint so that it is facing profile of gate perpendicularly
- Move a known x distance forward to go through gate on correct side while moving with roll velocity for style points
- profit

**Comment by ShaanGondalia** [comment]
Closing, stale issue.
