### ISSUE TITLE
Optimize control loop

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#323]
## Background

Our controls algorithm performs a lot of unnecessary calculations. Because of this, controls monopolizes the robot computer, causing performance losses across our other packages. We should do a full pass of the controls package, looking for ways to improve the performance of our algorithm. The [System Utils](https://github.com/DukeRobotics/robosub-ros/tree/master/onboard/catkin_ws/src/system_utils) package can be used to measure resources usage.

## Tasks
- [ ] Reduce PID Loop target frequency
  - Most controls scripts are running at 10 or 15Hz, whereas the target frequency of the PID loops is 100Hz. If movement performance doesn't take a hit, we should look into reducing the number of these calculations
- [ ] Move thruster calculation from callback to run loop in `thruster_controls.py`

**Comment by vedarshshah** [comment]
Will be addressed in #454. PID loops will be run every time a message is published to `/state`, which runs at 20Hz. Thruster allocations will be computed in the main controls loop, running at 20Hz.
