### ISSUE TITLE
Extract robot constants to config file

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#330]
## Background
By definition, PID constants and robot kinematic values are specific to a robot. Storing these magic values in code conflicts with the "robot agnostic" architecture that Controls was originally designed with. These constants should be extracted to a config file.  Controls already defines a structure for a config file describing a robot's thruster configuration. This structure should be extended to include robot constants (PID constants, maximum velocities, set-point ranges).

## Tasks
- [ ] Update [config schema](https://github.com/DukeRobotics/robosub-ros/blob/master/onboard/catkin_ws/src/controls/config/cthulhu.config) to support robot constants
- [ ] Remove robot constants from position and velocity launch files

**Comment by vedarshshah** [comment]
Will be done as part of #454.
