### ISSUE TITLE
CV Sonar Full Merge

### ISSUE THREAD

**Issue by ricohasgithub** [DukeRobotics/robosub-ros#410]
### Purpose

Currently, both cv (using stereo vision) and sonar each have their own methods of obtaining depth information given a target. This update aims to integrate the cv and sonar code bases together to create a unified way of detecting the position of detected objects in water, specifically by using sonar to complement cv's current abilities. In addition to the full sonar library, this merge will mainly concern the script ```depthai_sonar_spatial_detection.py``` and the respective launch file. The script ```depthai_sonar_spatial_detection.py``` will run the regular depthai cv detection code, and once an object comes into frame, it will make a request to the sonar library.

**Comment by vedarshshah** [comment]
Merged. Sonar code was put into `depthai_spatial_detection.py` and `depthai_sonar_spatial_detection.py` was deleted.
