### ISSUE TITLE
Figure out integration with ROS

### ISSUE THREAD

**Issue by davidAmiron** [DukeRobotics/robosub-ros#58]
Figure out how to integrate the simulator with ros inside docker

**Comment by puzzler7** [comment]
Need to get ros on personal computers to see and interact with a rosmaster inside the docker container.

Possibly useful links:
http://wiki.ros.org/turtlebot/Tutorials/indigo/Network%20Configuration docker as turtlebot
https://wiki.ros.org/ROS/NetworkSetup
https://forums.balena.io/t/accessing-ros-master-from-outside-the-container/3420/46
