### ISSUE TITLE
Figure out how to do underwater simulation

### ISSUE THREAD

**Issue by davidAmiron** [DukeRobotics/robosub-ros#59]
Figure out how to do underwater simulation in the simulator

**Comment by puzzler7** [comment]
Need to do buoyancy and drag forces.

http://www.forum.coppeliarobotics.com/viewtopic.php?t=2975
http://www.forum.coppeliarobotics.com/viewtopic.php?t=7754

http://www.forum.coppeliarobotics.com/viewtopic.php?f=9&t=433
