### ISSUE TITLE
Get Robot Drag Forces

### ISSUE THREAD

**Issue by davidAmiron** [DukeRobotics/robosub-ros#79]
We will need the drag forces on the robot to create the simulation in vrep

- Probably get them from Trevor?

**Comment by puzzler7** [comment]
Currently approximating drag coefs as 1.1  - basically assuming it's a cube with slightly higher drag.

**Comment by puzzler7** [comment]
Still using 1.1 as our drag coef, but perhaps rotational drag should have a different coef?
